apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe
  labels:
    app: tic-tac-toe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tic-tac-toe
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
      - name: tic-tac-toe
<<<<<<< HEAD
        image: ghcr.io/bader2424/tic-tac-game:9.0
=======
<<<<<<< HEAD
        image: ghcr.io/bader2424/tic-tac-game:sha-9f6524666e837c12243982f54de390336857efed
=======
        image: ghcr.io/bader2424/tic-tac-game:sha-9f6524666e837c12243982f54de390336857efed
>>>>>>> 72a1402c3ce9921714d4a5cb4b998e6b987d8567
>>>>>>> 333c8edd9fdc3413fb21194895f737e98a6d579a
        # Image will be automatically updated by CI/CD pipeline hhhhh
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: github-container-registry

      